<?php

/**
 *
 * Alternative PSR autoloader injected into Magento 1.x framework to load
 * namespaced classes from /lib folder as a standard Magento modules. Based 
 * on https://php-download.com/ downloads of necessary libraries.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @category   Northhub
 * @package    Northhub_Roivenue
 * @author     Stanislav Puffler, DiS. - stanislav.puffler@northhub.cz
 * @copyright  Copyright (c) 2018 NorthHUB (http://magento.northhub.cz)
 * 
 * @see https://php-download.com/
 *
 */

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInitf1180c957890f65b1416b853c8e0d84b::getLoader();
